// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',

        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf2PR3m74qlVW86VTBjooTW62OAqSXRww',
    appId: '1:1071696703674:web:e7454750463622fe411283',
    messagingSenderId: '1071696703674',
    projectId: 'parkeasy-64fd2',
    authDomain: 'parkeasy-64fd2.firebaseapp.com',
    storageBucket: 'parkeasy-64fd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI7JhFKpp8s7OuNy2kG87be0cW04hCsmY',
    appId: '1:1071696703674:android:79f6246b5801f12b411283',
    messagingSenderId: '1071696703674',
    projectId: 'parkeasy-64fd2',
    storageBucket: 'parkeasy-64fd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqk6UlTvz9b0ERhAq3bZYZBjpC9f0rYB4',
    appId: '1:1071696703674:ios:e91a1f91fe60c9b8411283',
    messagingSenderId: '1071696703674',
    projectId: 'parkeasy-64fd2',
    storageBucket: 'parkeasy-64fd2.firebasestorage.app',
    iosBundleId: 'com.example.parkEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqk6UlTvz9b0ERhAq3bZYZBjpC9f0rYB4',
    appId: '1:1071696703674:ios:e91a1f91fe60c9b8411283',
    messagingSenderId: '1071696703674',
    projectId: 'parkeasy-64fd2',
    storageBucket: 'parkeasy-64fd2.firebasestorage.app',
    iosBundleId: 'com.example.parkEasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf2PR3m74qlVW86VTBjooTW62OAqSXRww',
    appId: '1:1071696703674:web:0478b213f4df304f411283',
    messagingSenderId: '1071696703674',
    projectId: 'parkeasy-64fd2',
    authDomain: 'parkeasy-64fd2.firebaseapp.com',
    storageBucket: 'parkeasy-64fd2.firebasestorage.app',
  );

}